#This module for Shadowrocket
[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[MITM]
hostname = api.revenuecat.com, buy.itunes.apple.com, us-central1-alight-creative.cloudfunctions.net

[Script]
http-response https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses script-path=https://raw.githubusercontent.com/Win98Plus/Alight-Motion-Premium-Shadowrocket/refs/heads/main/AlightMotion.js, requires-body=true, timeout=5, tag=Alight Motion
#rewrite by Win98Plus
